site_name: Netbox Client
repo_url: https://github.com/Kaioguilherme1/netbox-client
repo_name: Kaioguilherme1/netbox-client
edit_uri: tree/main/docs/


theme: 
  name: material
  language: pt-BR
  palette:
    primary: deep_blue

markdown_extensions: 
  - attr_list


plugins: 
- mkdocstrings:
    default_handler: python
    handlers:
      python: 
        paths: [netboxcli]
        
      